### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by arbarbosa1979** [vevv/eat#1]
I have tested this program on Linux and Windows and the same error always appears, and I could not identify exactly where this error is.

```
 C:\Github\eat\eat
>_ py __main__.py -i "001teste.flac" -f ddp -b 1024
[03/26/22 21:52:57] INFO     Processing "001teste.flac"...                                                                            handler.py:48

Converting 001teste.flac to rf64 ---------------------------------------- 100% 0:00:00
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by vevv** [comment]
Please send a log with a `--debug` param enabled.

**Comment by arbarbosa1979** [comment]
> Please send a log with a `--debug` param enabled.

I found out what the error was, the script couldn't find the Dolby Encoding Engine, but after some changes it managed to locate the file.
